name = "api-emaction"
main = "src/worker.js"
compatibility_date = "2023-07-25"
usage_model = "bundled"
env = { }

[[d1_databases]]
binding = "d1" # i.e. available in your Worker on env.DB
database_name = "everyone-should-emo"
database_id = "90c783ed-5d24-427d-8401-ae4a8ad971f6"

[triggers]
crons = [ ]
